pipeline {
    agent any

    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                sh 'chmod + spring-boot-api-example-master/gradlew assemble'
            }
        }
        stage('Test') {
            steps {
                sh 'chmod + spring-boot-api-example-master/gradlew test'
            }
        }
    }
}
